import type { Metadata } from "next";
import { Syne, DM_Sans } from "next/font/google";
import "./globals.css";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${syne.variable} ${dmSans.variable} h-full`}>
      <head>
        <style>{`
          :root {
            --navy: #0A0F1E;
            --navy2: #111827;
            --accent: #6C63FF;
            --accent2: #A78BFA;
            --mint: #10B981;
            --amber: #F59E0B;
            --rose: #F43F5E;
            --surface: rgba(255,255,255,0.04);
            --border: rgba(255,255,255,0.08);
            --card: rgba(255,255,255,0.05);
          }
        `}</style>
      </head>
      <body className="min-h-full flex flex-col antialiased bg-[#0A0F1E] text-white font-sans">
        {children}
      </body>
    </html>
  );
}
